name: 'UNBL Geoanalytics v1 Deploy'
description: 'Deploy UNBL geoanalytics services (shared infra + stacman/pretiler/exactextract) to Azure'
author: 'WCMC DevOps Team'

inputs:
  environment:
    description: 'Deployment environment (staging, production)'
    required: true
  azure-credentials:
    description: 'Azure service principal credentials (JSON)'
    required: true
  geoanalytics-ref:
    description: 'Branch/tag to checkout from unbl-geoanalytics'
    required: false
    default: 'new-staging-deploy'
  location:
    description: 'Azure region (e.g. uksouth)'
    required: false
    default: 'uksouth'
  deploy-shared-infra:
    description: 'Deploy shared resources (storage + ACR + container environment)'
    required: false
    default: 'true'
  deploy-stacman:
    description: 'Deploy stacman service'
    required: false
    default: 'true'
  deploy-pretiler:
    description: 'Deploy pretiler service'
    required: false
    default: 'true'
  deploy-exactextract:
    description: 'Deploy exactextract service'
    required: false
    default: 'true'

outputs:
  deployment-status:
    description: 'Status of the deployment operation'
    value: ${{ steps.deploy-result.outputs.status }}
  deployment-duration:
    description: 'Duration of the deployment operation in seconds'
    value: ${{ steps.deploy-result.outputs.duration }}
  resource-group:
    description: 'Resource group used for deployment'
    value: ${{ steps.deploy-result.outputs.resource_group }}
  container-registry:
    description: 'ACR name used for deployment'
    value: ${{ steps.deploy-result.outputs.acr_name }}

runs:
  using: 'composite'
  steps:
    - name: Start timing
      id: start
      shell: bash
      run: echo "start_time=$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Checkout geoanalytics repo
      uses: actions/checkout@v4
      with:
        repository: unepwcmc/unbl-geoanalytics
        ref: ${{ inputs.geoanalytics-ref }}
        path: ./unbl-geoanalytics
        token: ${{ env.GH_TOKEN }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Deploy geoanalytics services (per-service deployment)
      shell: bash
      run: |
        set -euo pipefail

        # Deploy shared infrastructure if requested
        if [ "${{ inputs.deploy-shared-infra }}" == "true" ]; then
          echo "Deploying shared infrastructure..."
          INFRA_BICEP="./unbl-geoanalytics/azure/bicep/shared-infra.bicep"
          INFRA_PARAMS="./unbl-geoanalytics/azure/bicep/parameters/shared-infra.${{ inputs.environment }}.json"
          
          if [ ! -f "$INFRA_PARAMS" ]; then
            echo "Warning: Parameters file not found: $INFRA_PARAMS"
            echo "Using staging parameters as fallback"
            INFRA_PARAMS="./unbl-geoanalytics/azure/bicep/parameters/shared-infra.staging.json"
          fi
          
          DEPLOYMENT_NAME="geoanalytics-infra-${{ inputs.environment }}-$(date +%Y%m%d%H%M%S)"
          az deployment sub create \
            --location "${{ inputs.location }}" \
            --name "$DEPLOYMENT_NAME" \
            --template-file "$INFRA_BICEP" \
            --parameters @"$INFRA_PARAMS" \
            --output none
          echo "Shared infrastructure deployed"
        fi

        # Deploy stacman if requested
        if [ "${{ inputs.deploy-stacman }}" == "true" ]; then
          echo "Deploying stacman service..."
          chmod +x ./unbl-geoanalytics/stacman/azure/scripts/deploy.sh
          cd ./unbl-geoanalytics/stacman
          SKIP_INFRA_FLAG=""
          if [ "${{ inputs.deploy-shared-infra }}" != "true" ]; then
            SKIP_INFRA_FLAG="--skip-infra"
          fi
          ./azure/scripts/deploy.sh \
            --environment "${{ inputs.environment }}" \
            --location "${{ inputs.location }}" \
            $SKIP_INFRA_FLAG
          cd ../..
        fi

        # Deploy pretiler if requested
        if [ "${{ inputs.deploy-pretiler }}" == "true" ]; then
          echo "Deploying pretiler service..."
          chmod +x ./unbl-geoanalytics/pretiler/azure/scripts/deploy.sh
          cd ./unbl-geoanalytics/pretiler
          SKIP_INFRA_FLAG=""
          if [ "${{ inputs.deploy-shared-infra }}" != "true" ]; then
            SKIP_INFRA_FLAG="--skip-infra"
          fi
          ./azure/scripts/deploy.sh \
            --environment "${{ inputs.environment }}" \
            --location "${{ inputs.location }}" \
            $SKIP_INFRA_FLAG
          cd ../..
        fi

        # Deploy exactextract if requested
        if [ "${{ inputs.deploy-exactextract }}" == "true" ]; then
          echo "Deploying exactextract service..."
          chmod +x ./unbl-geoanalytics/exactextract/azure/scripts/deploy.sh
          cd ./unbl-geoanalytics/exactextract
          SKIP_INFRA_FLAG=""
          if [ "${{ inputs.deploy-shared-infra }}" != "true" ]; then
            SKIP_INFRA_FLAG="--skip-infra"
          fi
          ./azure/scripts/deploy.sh \
            --environment "${{ inputs.environment }}" \
            --location "${{ inputs.location }}" \
            $SKIP_INFRA_FLAG
          cd ../..
        fi

    - name: Logout of Azure
      shell: bash
      run: az logout || true

    - name: Set deployment result
      id: deploy-result
      shell: bash
      run: |
        set -euo pipefail
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - ${{ steps.start.outputs.start_time }}))
        echo "status=success" >> "$GITHUB_OUTPUT"
        echo "duration=$DURATION" >> "$GITHUB_OUTPUT"
        # Resource names come from the repo parameters file and/or Azure state.
        # Avoid duplicating naming logic here.
        echo "resource_group=" >> "$GITHUB_OUTPUT"
        echo "acr_name=" >> "$GITHUB_OUTPUT"


