name: 'UNBL Frontend v1 Deploy (From unbl-infrastructure repo)'
description: 'Deploy UNBL frontend - provisions infrastructure if needed, then deploys code'
author: 'WCMC DevOps Team'

inputs:
  environment:
    description: 'Deployment environment (staging, production)'
    required: true
  azure-credentials:
    description: 'Azure service principal credentials (JSON)'
    required: true
  infrastructure-ref:
    description: 'Branch/tag to checkout from unbl-infrastructure'
    required: false
    default: 'remove-stac-titiler'
  frontend-ref:
    description: 'Branch/tag to checkout from unbl-frontend'
    required: false
    default: 'new-staging-deploy'
  postgres-admin-password:
    description: 'PostgreSQL admin password (required for infrastructure provisioning)'
    required: true

outputs:
  deployment-status:
    description: 'Status of the deployment operation'
    value: ${{ steps.deploy-result.outputs.status }}
  deployment-duration:
    description: 'Duration of the deployment operation in seconds'
    value: ${{ steps.deploy-result.outputs.duration }}
  deployment-url:
    description: 'URL of the deployed application'
    value: ${{ steps.deploy-result.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Start timing
      id: start
      shell: bash
      run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Checkout frontend repo
      uses: actions/checkout@v4
      with:
        repository: unepwcmc/unbl-frontend
        ref: ${{ inputs.frontend-ref }}
        path: ./unbl-frontend
        token: ${{ env.GH_TOKEN }}

    - name: Checkout infrastructure repo
      uses: actions/checkout@v4
      with:
        repository: unepwcmc/unbl-infrastructure
        ref: ${{ inputs.infrastructure-ref }}
        path: ./unbl-infrastructure
        token: ${{ env.GH_TOKEN }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Provision infrastructure
      shell: bash
      working-directory: ./unbl-infrastructure/azure
      run: |
        RG="unbl-${{ inputs.environment }}-rg"
        ENV="${{ inputs.environment }}"
        
        echo "ðŸ—ï¸ Provisioning frontend infrastructure..."
        echo "âš ï¸ NOTE: This will provision ALL infrastructure (shared with backend)"
        
        # Create .env file with required secrets
        cat > .env << 'EOF'
        POSTGRES_ADMIN_PASSWORD=${{ inputs.postgres-admin-password }}
        MONGO_ADMIN_PASSWORD=${{ env.MONGO_ADMIN_PASSWORD }}
        AUTH0_CLIENT_ID=${{ env.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET=${{ env.AUTH0_CLIENT_SECRET }}
        AUTH0_APPLICATION_CLIENT_ID=${{ env.AUTH0_APPLICATION_CLIENT_ID }}
        AUTH0_EXTENSION_URL=${{ env.AUTH0_EXTENSION_URL }}
        SERVICE_API_KEY=${{ env.SERVICE_API_KEY }}
        SERVICE_API_READ_KEY=${{ env.SERVICE_API_READ_KEY }}
        GATSBY_MAPBOX_TOKEN=${{ env.GATSBY_MAPBOX_TOKEN }}
        EOF
        
        source .env
        
        # Deploy infrastructure using Bicep
        # The Bicep deployment is idempotent - safe to run multiple times
        ./scripts/deploy.sh --yes --skip-validation
        
        # Populate Key Vault secrets
        ./scripts/populate-secrets.sh
        
        echo "âœ… Infrastructure provisioned"

    - name: Deploy frontend using infrastructure script
      id: deploy
      shell: bash
      working-directory: ./unbl-infrastructure/azure
      env:
        # Pass environment variables to the script
        GATSBY_AUTH0_DOMAIN: ${{ env.GATSBY_AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ env.AUTH0_CLIENT_ID }}
        AUTH0_APPLICATION_CLIENT_ID: ${{ env.AUTH0_APPLICATION_CLIENT_ID }}
        GATSBY_AUTH0_AUDIENCE: ${{ env.GATSBY_AUTH0_AUDIENCE }}
        GATSBY_MAPBOX_TOKEN: ${{ env.GATSBY_MAPBOX_TOKEN }}
      run: |
        RG="unbl-${{ inputs.environment }}-rg"
        
        echo "Deploying frontend using deploy-frontend-full.sh..."
        echo "  Resource Group: $RG"
        
        # The deploy-frontend-full.sh script handles:
        # - Creating .env with Auth0 and Mapbox config
        # - Getting storage account from Azure
        # - Building earth-map and earth-admin
        # - Uploading to Azure Storage
        # - Enabling static website hosting
        # - Printing URLs (Map and Admin)
        ./scripts/deploy-frontend-full.sh

    - name: Run health checks
      shell: bash
      working-directory: ./unbl-infrastructure/azure
      run: |
        RG="unbl-${{ inputs.environment }}-rg"
        ENV="${{ inputs.environment }}"
        
        echo "Running health checks..."
        ./scripts/health-check.sh --resource-group "$RG" --environment "$ENV" || {
          echo "âš ï¸ Some health checks failed"
          echo "Frontend may need more time to initialize"
        }

    - name: Set deployment result
      id: deploy-result
      shell: bash
      working-directory: ./unbl-infrastructure/azure
      run: |
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - ${{ steps.start.outputs.start_time }}))
        
        # Get frontend URL from deployment outputs
        RG="unbl-${{ inputs.environment }}-rg"
        STORAGE_ACCOUNT=$(az storage account list \
          --resource-group "$RG" \
          --query "[?contains(name, 'frontend')].name" -o tsv | head -1)
        FRONTEND_URL="https://${STORAGE_ACCOUNT}.z33.web.core.windows.net/"
        
        echo "status=success" >> $GITHUB_OUTPUT
        echo "duration=$DURATION" >> $GITHUB_OUTPUT
        echo "url=$FRONTEND_URL" >> $GITHUB_OUTPUT
        
        echo "âœ… Deployment complete!"
        echo "   Duration: ${DURATION}s"
        echo "   Frontend URL: $FRONTEND_URL"

