name: Deploy with Kamal v2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RUBY_VERSION: '3.2.2'
  KAMAL_VERSION: '2.0.0'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production  # This enables environment secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal -v ${{ env.KAMAL_VERSION }}

      - name: Validate and Populate Secrets
        uses: unepwcmc/devops-actions/.github/actions/validate-secrets@v1
        with:
          secrets-file: '.kamal/secrets-common'
          environment: 'production'

      - name: Deploy with Kamal
        run: kamal deploy
        env:
          KAMAL_REGISTRY_USERNAME: ${{ env.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ env.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ env.RAILS_MASTER_KEY }}
          DATABASE_HOSTNAME: ${{ env.DATABASE_HOSTNAME }}
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ env.DATABASE_PORT }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }} 