name: Test Validate Secrets Action

on:
  workflow_dispatch:
    inputs:
      test-case:
        description: 'Test case to run'
        required: true
        type: choice
        options:
          - missing-file
          - missing-secrets
          - valid-secrets
          - all

jobs:
  test:
    name: Test Validate Secrets
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup test environment
        if: inputs.test-case == 'missing-file' || inputs.test-case == 'all'
        run: |
          rm -f .kamal/secrets-common

      - name: Setup test environment
        if: inputs.test-case == 'missing-secrets' || inputs.test-case == 'all'
        run: |
          mkdir -p .kamal
          cp .kamal/secrets-common.template .kamal/secrets-common

      - name: Setup test environment
        if: inputs.test-case == 'valid-secrets' || inputs.test-case == 'all'
        run: |
          mkdir -p .kamal
          cp .kamal/secrets-common.template .kamal/secrets-common
          # Add test secrets to environment
          echo "KAMAL_REGISTRY_USERNAME=test" >> $GITHUB_ENV
          echo "KAMAL_REGISTRY_PASSWORD=test" >> $GITHUB_ENV
          echo "RAILS_MASTER_KEY=test" >> $GITHUB_ENV
          echo "DATABASE_HOSTNAME=test" >> $GITHUB_ENV
          echo "DATABASE_NAME=test" >> $GITHUB_ENV
          echo "DATABASE_USERNAME=test" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=test" >> $GITHUB_ENV
          echo "DATABASE_PORT=test" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=test" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=test" >> $GITHUB_ENV
          echo "AWS_REGION=test" >> $GITHUB_ENV

      - name: Test missing file
        if: inputs.test-case == 'missing-file' || inputs.test-case == 'all'
        uses: unepwcmc/devops-actions/.github/actions/validate-secrets@v1
        with:
          secrets-file: '.kamal/secrets-common'
          environment: 'test'
        continue-on-error: true

      - name: Test missing secrets
        if: inputs.test-case == 'missing-secrets' || inputs.test-case == 'all'
        uses: unepwcmc/devops-actions/.github/actions/validate-secrets@v1
        with:
          secrets-file: '.kamal/secrets-common'
          environment: 'test'
        continue-on-error: true

      - name: Test valid secrets
        if: inputs.test-case == 'valid-secrets' || inputs.test-case == 'all'
        uses: unepwcmc/devops-actions/.github/actions/validate-secrets@v1
        with:
          secrets-file: '.kamal/secrets-common'
          environment: 'test'

      - name: Verify environment variables
        if: inputs.test-case == 'valid-secrets' || inputs.test-case == 'all'
        run: |
          # Check if environment variables are set
          if [ -z "$KAMAL_REGISTRY_USERNAME" ]; then
            echo "::error::KAMAL_REGISTRY_USERNAME not set"
            exit 1
          fi
          if [ -z "$KAMAL_REGISTRY_PASSWORD" ]; then
            echo "::error::KAMAL_REGISTRY_PASSWORD not set"
            exit 1
          fi
          # Add more checks as needed 